const MAX_TEXT=50000;
const RULES=[
{id:"instruction_override",severity:"high",weight:34,re:/\b(ignore|disregard|override|forget)\b.{0,60}\b(previous|prior|system|developer|safety|instructions?|rules?)\b/gi,behavior:"Attempts to override higher-priority instructions"},
{id:"secret_request",severity:"high",weight:42,re:/\b(send|share|provide|reveal|include|paste|upload|forward|export|collect|retrieve)\b.{0,80}\b(passwords?|passcodes?|private keys?|seed phrases?|recovery codes?|api keys?|auth(?:entication)? cookies?|credentials?|ssn|cvv|cvc)\b/gi,behavior:"Requests secrets or credentials"},
{id:"data_exfiltration",severity:"high",weight:38,re:/\b(send|forward|upload|post|email|share|export)\b.{0,100}\b(files?|documents?|emails?|messages?|contacts?|calendar|records?|logs?|internal notes?|customer data)\b.{0,100}\b(to|via|at)\b/gi,behavior:"Requests outbound disclosure of data"},
{id:"authority_claim",severity:"medium",weight:18,re:/\b(i am|i'm|this is|speaking as)\b.{0,60}\b(admin(?:istrator)?|owner|security team|developer|manager|ceo|compliance|support)\b|\b(already approved|pre[- ]?approved|authorized by|management approved)\b/gi,behavior:"Claims authority or prior approval inside untrusted content"},
{id:"concealment",severity:"high",weight:31,re:/\b(do not|don't|never)\b.{0,60}\b(tell|notify|mention|disclose|log|record|show)\b|\b(keep (?:this|it) secret|omit this|without (?:their|the user's|user) knowledge)\b/gi,behavior:"Requests concealment or suppression"},
{id:"delayed_side_effect",severity:"medium",weight:22,re:/\b(later|next time|during the next|when .{0,40} happens?|after .{0,40})\b.{0,120}\b(send|delete|upload|transfer|purchase|pay|invite|forward|change|update)\b/gi,behavior:"Defers a side effect to a later trigger"},
{id:"tool_control",severity:"medium",weight:24,re:/\b(use|call|invoke|run|execute|open)\b.{0,60}\b(tool|terminal|shell|bash|browser|integration|api)\b|\b(click|submit)\b.{0,40}\b(button|link|form)\b/gi,behavior:"Attempts to direct tool or UI use"},
{id:"money_action",severity:"high",weight:35,re:/\b(pay|purchase|buy|transfer|withdraw|bridge|swap|send)\b.{0,60}\b(money|funds?|tokens?|crypto|usd[c|t]?|eth|btc|card|wallet)\b/gi,behavior:"Requests a money or wallet action"},
{id:"urgency_pressure",severity:"low",weight:9,re:/\b(urgent|immediately|right now|without delay|time[- ]sensitive|act now|do not pause)\b/gi,behavior:"Uses urgency pressure"},
{id:"external_fetch",severity:"medium",weight:17,re:/\b(download|fetch|open|visit|follow)\b.{0,50}\b(https?:\/\/|link|url|attachment|file)\b/gi,behavior:"Directs retrieval from another source"}
] as const;
export function scanInput(input:any){if(!input||typeof input!=="object"||typeof input.text!=="string")throw new Error("Body must contain a text string.");if(!input.text.trim()||input.text.length>MAX_TEXT)throw new Error(`text must contain 1-${MAX_TEXT} characters.`);const matches:any[]=[];for(const rule of RULES){rule.re.lastIndex=0;let hit;while((hit=rule.re.exec(input.text))&&matches.length<100){matches.push({ruleId:rule.id,severity:rule.severity,behavior:rule.behavior,start:hit.index,end:hit.index+hit[0].length,evidence:hit[0].replace(/\s+/g," ").trim().slice(0,240)});if(!hit[0].length)rule.re.lastIndex++;}}const unique=[...new Set(matches.map(m=>m.ruleId))],score=Math.min(100,unique.reduce((s,id)=>s+(RULES.find(r=>r.id===id)?.weight||0),0)),verdict=score>=60||matches.some(m=>m.severity==="high")?"block":score>=20?"review":"allow";return{schemaVersion:"1.0",verdict,riskScore:score,sourceType:typeof input.sourceType==="string"?input.sourceType.slice(0,40):"unspecified",matchedBehaviors:unique,matches,limits:{heuristicOnly:true,maxCharacters:MAX_TEXT},note:"Deterministic heuristic lint only. It can miss attacks and produce false positives; treat allow as no match, not proof of safety. No input is retained or fetched."};}
